// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQSDevtISRHS406Nuq1TvKHjEaUzVTQzI',
    appId: '1:643152928655:web:811d5d597ed50b17b735fa',
    messagingSenderId: '643152928655',
    projectId: 'anti-school-test',
    authDomain: 'anti-school-test.firebaseapp.com',
    storageBucket: 'anti-school-test.appspot.com',
    measurementId: 'G-JYTYVXPBJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBarDQo63qHqxckb-AP76VNGi7zAx5Epac',
    appId: '1:643152928655:android:1d525dcf355635c8b735fa',
    messagingSenderId: '643152928655',
    projectId: 'anti-school-test',
    storageBucket: 'anti-school-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHzdqApUCJP0zcno_SdWwqpGjqkgU8U4',
    appId: '1:643152928655:ios:d3fed862a2d6c665b735fa',
    messagingSenderId: '643152928655',
    projectId: 'anti-school-test',
    storageBucket: 'anti-school-test.appspot.com',
    iosBundleId: 'com.example.antiSchoolTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHzdqApUCJP0zcno_SdWwqpGjqkgU8U4',
    appId: '1:643152928655:ios:d3fed862a2d6c665b735fa',
    messagingSenderId: '643152928655',
    projectId: 'anti-school-test',
    storageBucket: 'anti-school-test.appspot.com',
    iosBundleId: 'com.example.antiSchoolTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQSDevtISRHS406Nuq1TvKHjEaUzVTQzI',
    appId: '1:643152928655:web:7dc2920b6b83aafcb735fa',
    messagingSenderId: '643152928655',
    projectId: 'anti-school-test',
    authDomain: 'anti-school-test.firebaseapp.com',
    storageBucket: 'anti-school-test.appspot.com',
    measurementId: 'G-CF1WZGX3KS',
  );
}
